---
- name: play for installing postgresql
  hosts: db_hosts
  become: true
  gather_facts: no
  handlers:
    - name: restart postgresql
      service: name=postgresql state=restarted
  tasks:
    - name: Install postgres and related modules
      apt: name={{ item }} update_cache=true state=installed
      with_items:
        - postgresql
        - postgresql-contrib
        - libpq-dev
        - python-psycopg2
    - name: postgresql should listen on all ports
      lineinfile: dest=/etc/postgresql/9.3/main/postgresql.conf
                  regexp="^listen_addresses"
                  line="listen_addresses = '*'" state=present
    - name: postgresql should allow access to host
      copy:
        dest: /etc/postgresql/9.3/main/pg_hba.conf
        content: |
          local   all   postgres   peer
          local   all   all        md5
          host    all   all        0.0.0.0/0   md5
      notify: restart postgresql

- name: Play for setting up with database
  hosts: db_hosts
  become: true
  become_user: postgres
  gather_facts: no
  vars:
    dbname: my_app
    dbuser: my_app_user
    dbpassword: mysupersecretpassword
  tasks:
    - name: ensure database is created
      postgresql_db: name={{dbname}} login_user=postgres
    - name: ensure user has access to database
      postgresql_user: db={{dbname}} name={{dbuser}} password={{dbpassword}} encrypted=false priv=ALL

- name: Play for setting up node js in service
  hosts: service_hosts
  become: true
  tasks:
    - name: add apt key for nodesource
      apt_key:
        url: https://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x1655A0AB68576280
        id: "68576280"
        state: present
        validate_certs: no
    - name: add repo for nodesource
      apt_repository:
        repo: 'deb https://deb.nodesource.com/node_0.10 {{ ansible_distribution_release }} main'
        update_cache: yes

    - name: install nodejs
      apt: name=nodejs update_cache=yes

- name: Play for setting up npm modules including our app in service
  hosts: service_hosts
  become: true
  tasks:
    - name: Install express
      npm: name=express registry=https://registry.npmjs.org global=yes
#    - name: Install my app
      # npm: name=myapp registry=https://registry.myapp.org
